import ManageUsersUI from "@/components/super-admin/manage-users";

export default function Users() {
  const data = [
    {
      id: "1",
      name: "John Doe",
      email: "Johndoe@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-01",
      action: "Edit",
    },
    {
      id: "2",
      name: "Wick Pendragon",
      email: "Pendragon@gmail.com",
      role: "ApplicantAdmin",
      createdAt: "2026-07-02",
      action: "Edit",
    },
    {
      id: "3",
      name: "Caesar Doom",
      email: "Doom@gmail.com",
      role: "VehicleAdmin",
      createdAt: "2026-07-01",
      action: "Edit",
    },
    {
      id: "4",
      name: "Cvini Castrei",
      email: "Castrei@gmail.com",
      role: "SuperAdmin",
      createdAt: "2026-07-01",
      action: "Edit",
    },
    {
      id: "5",
      name: "Elena Voss",
      email: "Voss@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-03",
      action: "Edit",
    },
    {
      id: "6",
      name: "Marcus Reyes",
      email: "Reyes@gmail.com",
      role: "VehicleAdmin",
      createdAt: "2026-07-03",
      action: "Edit",
    },
    {
      id: "7",
      name: "Priya Sundaram",
      email: "Sundaram@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-04",
      action: "Edit",
    },
    {
      id: "8",
      name: "Diego Alvarado",
      email: "Alvarado@gmail.com",
      role: "ApplicantAdmin",
      createdAt: "2026-07-04",
      action: "Edit",
    },
    {
      id: "9",
      name: "Naomi Cruz",
      email: "Cruz@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-05",
      action: "Edit",
    },
    {
      id: "10",
      name: "Julian Fontaine",
      email: "Fontaine@gmail.com",
      role: "SuperAdmin",
      createdAt: "2026-07-05",
      action: "Edit",
    },
    {
      id: "11",
      name: "Aiko Tanaka",
      email: "Tanaka@gmail.com",
      role: "VehicleAdmin",
      createdAt: "2026-07-06",
      action: "Edit",
    },
    {
      id: "12",
      name: "Samuel Okafor",
      email: "Okafor@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-06",
      action: "Edit",
    },
    {
      id: "13",
      name: "Isabelle Moreau",
      email: "Moreau@gmail.com",
      role: "ApplicantAdmin",
      createdAt: "2026-07-07",
      action: "Edit",
    },
    {
      id: "14",
      name: "Theo Bracken",
      email: "Bracken@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-07",
      action: "Edit",
    },
    {
      id: "15",
      name: "Renata Silva",
      email: "Silva@gmail.com",
      role: "VehicleAdmin",
      createdAt: "2026-07-08",
      action: "Edit",
    },
    {
      id: "16",
      name: "Oscar Lindqvist",
      email: "Lindqvist@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-08",
      action: "Edit",
    },
    {
      id: "17",
      name: "Yuki Matsumoto",
      email: "Matsumoto@gmail.com",
      role: "ApplicantAdmin",
      createdAt: "2026-07-09",
      action: "Edit",
    },
    {
      id: "18",
      name: "Camille Dubois",
      email: "Dubois@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-09",
      action: "Edit",
    },
    {
      id: "19",
      name: "Nathaniel Pierce",
      email: "Pierce@gmail.com",
      role: "SuperAdmin",
      createdAt: "2026-07-10",
      action: "Edit",
    },
    {
      id: "20",
      name: "Farah Haddad",
      email: "Haddad@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-10",
      action: "Edit",
    },
    {
      id: "21",
      name: "Gabriel Marsh",
      email: "Marsh@gmail.com",
      role: "VehicleAdmin",
      createdAt: "2026-07-11",
      action: "Edit",
    },
    {
      id: "22",
      name: "Selin Kaya",
      email: "Kaya@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-11",
      action: "Edit",
    },
    {
      id: "23",
      name: "Ronan Whitfield",
      email: "Whitfield@gmail.com",
      role: "ApplicantAdmin",
      createdAt: "2026-07-12",
      action: "Edit",
    },
    {
      id: "24",
      name: "Mei Lin Zhao",
      email: "Zhao@gmail.com",
      role: "Applicant",
      createdAt: "2026-07-12",
      action: "Edit",
    },
  ];
  return (
    <div>
      <ManageUsersUI data={data} />
    </div>
  );
}
