export const SERVICE_ID = {
  AGRICULTURAL: 1,
  RESIDENTIAL: 2,
  TREE_CUTTING: 3,
  CHAINSAW: 4,
};

export const SERVICE_PREFIX = {
  [SERVICE_ID.AGRICULTURAL]: "AFPF",
  [SERVICE_ID.RESIDENTIAL]: "RFPF",
  [SERVICE_ID.TREE_CUTTING]: "TCPF",
  [SERVICE_ID.CHAINSAW]: "CRF",
};
