/**
 * Philippine Standard Geographic Code (PSGC) reference data for Pampanga province.
 * Source: PhilAtlas (https://www.philatlas.com/lists/barangays-pampanga.html), 2020 barangay list.
 * Covers the 19 municipalities + 2 component cities of Pampanga (505 barangays total).
 * Angeles City is a highly urbanized city administratively independent of the province
 * and is intentionally excluded, matching official PSA/PSGC groupings.
 *
 * Structure is nested by province so more provinces can be added later without
 * changing the shape consumers rely on.
 */

export const PROVINCES = ["Pampanga"];

export const DEFAULT_PROVINCE = "Pampanga";

const PAMPANGA_BARANGAYS = {
  "Apalit": [
    "Balucuc",
    "Calantipe",
    "Cansinala",
    "Capalangan",
    "Colgante",
    "Paligui",
    "Sampaloc",
    "San Juan",
    "San Vicente",
    "Sucad",
    "Sulipan",
    "Tabuyuc",
  ],
  "Arayat": [
    "Arenas",
    "Baliti",
    "Batasan",
    "Buensuceso",
    "Candating",
    "Cupang",
    "Gatiawin",
    "Guemasan",
    "Kaledian",
    "La Paz",
    "Lacmit",
    "Lacquios",
    "Mangga-Cacutud",
    "Mapalad",
    "Matamo",
    "Panlinlang",
    "Paralaya",
    "Plazang Luma",
    "Poblacion",
    "San Agustin Norte",
    "San Agustin Sur",
    "San Antonio",
    "San Jose Mesulo",
    "San Juan Bano",
    "San Mateo",
    "San Nicolas",
    "San Roque Bitas",
    "Santo Niño Tabuan",
    "Suclayin",
    "Telapayong",
  ],
  "Bacolor": [
    "Balas",
    "Cabalantian",
    "Cabambangan",
    "Cabetican",
    "Calibutbut",
    "Concepcion",
    "Dolores",
    "Duat",
    "Macabacle",
    "Magliman",
    "Maliwalu",
    "Mesalipit",
    "Parulog",
    "Potrero",
    "San Antonio",
    "San Isidro",
    "San Vicente",
    "Santa Barbara",
    "Santa Ines",
    "Talba",
    "Tinajero",
  ],
  "Candaba": [
    "Bahay Pare",
    "Bambang",
    "Barangca",
    "Barit",
    "Buas",
    "Cuayang Bugtong",
    "Dalayap",
    "Dulong Ilog",
    "Gulap",
    "Lanang",
    "Lourdes",
    "Magumbali",
    "Mandasig",
    "Mandili",
    "Mangga",
    "Mapaniqui",
    "Paligui",
    "Pangclara",
    "Pansinao",
    "Paralaya",
    "Pasig",
    "Pescadores",
    "Pulong Gubat",
    "Pulong Palazan",
    "Salapungan",
    "San Agustin",
    "Santo Rosario",
    "Tagulod",
    "Talang",
    "Tenejero",
    "Vizal San Pablo",
    "Vizal Santo Cristo",
    "Vizal Santo Niño",
  ],
  "Floridablanca": [
    "Anon",
    "Apalit",
    "Basa Air Base",
    "Benedicto",
    "Bodega",
    "Cabangcalan",
    "Calantas",
    "Carmencita",
    "Consuelo",
    "Dampe",
    "Del Carmen",
    "Fortuna",
    "Gutad",
    "Mabical",
    "Maligaya",
    "Mawacat",
    "Nabuclod",
    "Pabanlag",
    "Paguiruan",
    "Palmayo",
    "Pandaguirig",
    "Poblacion",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Nicolas",
    "San Pedro",
    "San Ramon",
    "San Roque",
    "Santa Monica",
    "Santo Rosario",
    "Solib",
    "Valdez",
  ],
  "Guagua": [
    "Ascomo",
    "Bancal",
    "Jose Abad Santos",
    "Lambac",
    "Magsaysay",
    "Maquiapo",
    "Natividad",
    "Plaza Burgos",
    "Pulungmasle",
    "Rizal",
    "San Agustin",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Juan Bautista",
    "San Juan Nepomuceno",
    "San Matias",
    "San Miguel",
    "San Nicolas 1st",
    "San Nicolas 2nd",
    "San Pablo",
    "San Pedro",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Filomena",
    "Santa Ines",
    "Santa Ursula",
    "Santo Cristo",
    "Santo Niño",
  ],
  "Lubao": [
    "Balantacan",
    "Bancal Pugad",
    "Bancal Sinubli",
    "Baruya",
    "Calangain",
    "Concepcion",
    "De La Paz",
    "Del Carmen",
    "Don Ignacio Dimson",
    "Lourdes",
    "Prado Siongco",
    "Remedios",
    "San Agustin",
    "San Antonio",
    "San Francisco",
    "San Isidro",
    "San Jose Apunan",
    "San Jose Gumi",
    "San Juan",
    "San Matias",
    "San Miguel",
    "San Nicolas 1st",
    "San Nicolas 2nd",
    "San Pablo 1st",
    "San Pablo 2nd",
    "San Pedro Palcarangan",
    "San Pedro Saug",
    "San Roque Arbol",
    "San Roque Dau",
    "San Vicente",
    "Santa Barbara",
    "Santa Catalina",
    "Santa Cruz",
    "Santa Lucia",
    "Santa Maria",
    "Santa Monica",
    "Santa Rita",
    "Santa Teresa 1st",
    "Santa Teresa 2nd",
    "Santiago",
    "Santo Cristo",
    "Santo Domingo",
    "Santo Niño",
    "Santo Tomas",
  ],
  "Mabalacat City": [
    "Atlu-Bola",
    "Bical",
    "Bundagul",
    "Cacutud",
    "Calumpang",
    "Camachiles",
    "Dapdap",
    "Dau",
    "Dolores",
    "Duquit",
    "Lakandula",
    "Mabiga",
    "Macapagal Village",
    "Mamatitang",
    "Mangalit",
    "Marcos Village",
    "Mawaque",
    "Paralayunan",
    "Poblacion",
    "San Francisco",
    "San Joaquin",
    "Santa Ines",
    "Santa Maria",
    "Santo Rosario",
    "Sapang Balen",
    "Sapang Biabas",
    "Tabun",
  ],
  "Macabebe": [
    "Batasan",
    "Caduang Tete",
    "Candelaria",
    "Castuli",
    "Consuelo",
    "Dalayap",
    "Mataguiti",
    "San Esteban",
    "San Francisco",
    "San Gabriel",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santa Lutgarda",
    "Santa Maria",
    "Santa Rita",
    "Santo Niño",
    "Santo Rosario",
    "Saplad David",
    "Tacasan",
    "Telacsan",
  ],
  "Magalang": [
    "Ayala",
    "Bucanan",
    "Camias",
    "Dolores",
    "Escaler",
    "La Paz",
    "Navaling",
    "San Agustin",
    "San Antonio",
    "San Franciso",
    "San Ildefonso",
    "San Isidro",
    "San Jose",
    "San Miguel",
    "San Nicolas 1st",
    "San Nicolas 2nd",
    "San Pablo",
    "San Pedro I",
    "San Pedro II",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santa Lucia",
    "Santa Maria",
    "Santo Niño",
    "Santo Rosario",
    "Turu",
  ],
  "Masantol": [
    "Alauli",
    "Bagang",
    "Balibago",
    "Bebe Anac",
    "Bebe Matua",
    "Bulacus",
    "Cambasi",
    "Malauli",
    "Nigui",
    "Palimpe",
    "Puti",
    "Sagrada",
    "San Agustin",
    "San Isidro Anac",
    "San Isidro Matua",
    "San Nicolas",
    "San Pedro",
    "Santa Cruz",
    "Santa Lucia Anac",
    "Santa Lucia Matua",
    "Santa Lucia Paguiba",
    "Santa Lucia Wakas",
    "Santa Monica",
    "Santo Niño",
    "Sapang Kawayan",
    "Sua",
  ],
  "Mexico": [
    "Acli",
    "Anao",
    "Balas",
    "Buenavista",
    "Camuning",
    "Cawayan",
    "Concepcion",
    "Culubasa",
    "Divisoria",
    "Dolores",
    "Eden",
    "Gandus",
    "Lagundi",
    "Laput",
    "Laug",
    "Masamat",
    "Masangsang",
    "Nueva Victoria",
    "Pandacaqui",
    "Pangatlan",
    "Panipuan",
    "Parian",
    "Sabanilla",
    "San Antonio",
    "San Carlos",
    "San Jose Malino",
    "San Jose Matulid",
    "San Juan",
    "San Lorenzo",
    "San Miguel",
    "San Nicolas",
    "San Pablo",
    "San Patricio",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Cruz",
    "Santa Maria",
    "Santo Domingo",
    "Santo Rosario",
    "Sapang Maisac",
    "Suclaban",
    "Tangle",
  ],
  "Minalin": [
    "Bulac",
    "Dawe",
    "Lourdes",
    "Maniango",
    "San Francisco 1st",
    "San Francisco 2nd",
    "San Isidro",
    "San Nicolas",
    "San Pedro",
    "Santa Catalina",
    "Santa Maria",
    "Santa Rita",
    "Santo Domingo",
    "Santo Rosario",
    "Saplad",
  ],
  "Porac": [
    "Babo Pangulo",
    "Babo Sacan",
    "Balubad",
    "Calzadang Bayu",
    "Camias",
    "Cangatba",
    "Diaz",
    "Dolores",
    "Inararo",
    "Jalung",
    "Mancatian",
    "Manibaug Libutad",
    "Manibaug Paralaya",
    "Manibaug Pasig",
    "Manuali",
    "Mitla Proper",
    "Palat",
    "Pias",
    "Pio",
    "Planas",
    "Poblacion",
    "Pulong Santol",
    "Salu",
    "San Jose Mitla",
    "Santa Cruz",
    "Sapang Uwak",
    "Sepung Bulaun",
    "Sinura",
    "Villa Maria",
  ],
  "City of San Fernando": [
    "Alasas",
    "Baliti",
    "Bulaon",
    "Calulut",
    "Del Carmen",
    "Del Pilar",
    "Del Rosario",
    "Dela Paz Norte",
    "Dela Paz Sur",
    "Dolores",
    "Juliana",
    "Lara",
    "Lourdes",
    "Magliman",
    "Maimpis",
    "Malino",
    "Malpitic",
    "Pandaras",
    "Panipuan",
    "Pulung Bulu",
    "Quebiauan",
    "Saguin",
    "San Agustin",
    "San Felipe",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Nicolas",
    "San Pedro",
    "Santa Lucia",
    "Santa Teresita",
    "Santo Niño",
    "Santo Rosario",
    "Sindalan",
    "Telabastagan",
  ],
  "San Luis": [
    "San Agustin",
    "San Carlos",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Nicolas",
    "San Roque",
    "San Sebastian",
    "Santa Catalina",
    "Santa Cruz Pambilog",
    "Santa Cruz Poblacion",
    "Santa Lucia",
    "Santa Monica",
    "Santa Rita",
    "Santo Niño",
    "Santo Rosario",
    "Santo Tomas",
  ],
  "San Simon": [
    "Concepcion",
    "De La Paz",
    "San Agustin",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Miguel",
    "San Nicolas",
    "San Pablo Libutad",
    "San Pablo Proper",
    "San Pedro",
    "Santa Cruz",
    "Santa Monica",
    "Santo Niño",
  ],
  "Santa Ana": [
    "San Agustin",
    "San Bartolome",
    "San Isidro",
    "San Joaquin",
    "San Jose",
    "San Juan",
    "San Nicolas",
    "San Pablo",
    "San Pedro",
    "San Roque",
    "Santa Lucia",
    "Santa Maria",
    "Santiago",
    "Santo Rosario",
  ],
  "Santa Rita": [
    "Becuran",
    "Dila-dila",
    "San Agustin",
    "San Basilio",
    "San Isidro",
    "San Jose",
    "San Juan",
    "San Matias",
    "San Vicente",
    "Santa Monica",
  ],
  "Santo Tomas": [
    "Moras de La Paz",
    "Poblacion",
    "San Bartolome",
    "San Matias",
    "San Vicente",
    "Santo Rosario",
    "Sapa",
  ],
  "Sasmuan": [
    "Batang 1st",
    "Batang 2nd",
    "Mabuanbuan",
    "Malusac",
    "Sabitanan",
    "San Antonio",
    "San Nicolas 1st",
    "San Nicolas 2nd",
    "San Pedro",
    "Santa Lucia",
    "Santa Monica",
    "Santo Tomas",
  ],
};

/**
 * Master address tree: province -> municipality/city -> barangays.
 * Add another province as a sibling key to extend beyond Pampanga.
 */
export const PH_ADDRESS_DATA = {
  Pampanga: PAMPANGA_BARANGAYS,
};

/**
 * Returns the sorted list of municipality/city names for a given province.
 * Returns an empty array if the province is unknown.
 */
export function getMunicipalities(province) {
  const entry = PH_ADDRESS_DATA[province];
  if (!entry) return [];
  return Object.keys(entry).sort();
}

/**
 * Returns the sorted list of barangays for a given province + municipality/city.
 * Returns an empty array if the province or municipality is unknown.
 */
export function getBarangays(province, municipality) {
  const entry = PH_ADDRESS_DATA[province]?.[municipality];
  if (!entry) return [];
  return [...entry].sort();
}